name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:     # Allows manual trigger
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          user: SahinDa
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_languages: yes
